#!/bin/bash

# Copyright (c) 2015 Jascha Silbermann [http://jsilber.net]

backup_dir="${BACKUP_HOME}/wp/install"

now=`date "+%Y-%m-%d_%H-%M-%S"`
backup_file="${MAIN_SITE}_${now}.install.tar.gz"

echo "Backing up $backup_file to $backup_dir ..."

tar -cpzf "${backup_dir}/${backup_file}" "$WP_HOME"

echo "Done."